---
homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - caskroom/versions

homebrew_installed_packages:
  - bash
  - bash-completion
  - coreutils
  - name: emacs
    install_options: with-cocoa,with-gnutls,with-imagemagick,with-libsrvg
  - fswatch
  - git
  - git-extras
  - go
  - gradle
  - grep
  - hub
  - iproute2mac
  - jq
  - nmap
  - patchutils
  - pyenv
  - pyenv-virtualenv
  - shellcheck
  - rsync
  - watch
  - xhyve
  - xz

homebrew_cask_apps:
  - alfred
  - dash
  - docker
  - google-backup-and-sync
  - google-cloud-sdk
  - google-chrome
  - google-chrome-canary
  - hammerspoon
  - iterm2
  - java
  - minikube
  - rescuetime
  - spotify
  - virtualbox
  - viscosity
  - xscreensaver

mas_installed_apps:
  - id: 803453959
    name: "Slack"
  - id: 443987910
    name: "1Password"
  - id: 834979136
    name: "Ethernet Status"

mas_email: ""
mas_password: ""
