---
homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-versions

homebrew_installed_packages:
  - bash
  - bash-completion
  - cloc
  - colordiff
  - coreutils
  - fswatch
  - git
  - git-extras
  - git-secret
  - gnu-sed
  - gpg2
  - go
  - go@1.12
  - grep
  - hub
  - iproute2mac
  - jq
  - kubernetes-cli
  - kubernetes-helm
  - moreutils
  - nmap
  - patchutils
  - pinentry-mac
  - pyenv
  - pyenv-virtualenv
  - shellcheck
  - rsync
  - watch
  - xz

homebrew_cask_apps:
  - alfred
  - dash
  - docker
  - emacs
  - firefox-developer-edition
  - firefox-nightly
  - firefox
  - google-backup-and-sync
  - google-cloud-sdk
  - google-chrome
  - google-chrome-canary
  - hammerspoon
  - iterm2
  - keybase
  - java
  - spotify
  - viscosity
  - xscreensaver

mas_installed_apps:
  - id: 803453959
    name: "Slack"
  - id: 1333542190
    name: "1Password 7"
  - id: 834979136
    name: "Ethernet Status"

mas_email: ""
mas_password: ""
