---
- hosts: all
  connection: local

  vars_files:
    - config.yml

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']

  tasks:
    - include_tasks: tasks/source-code-pro.yml
      tags: ['fonts']
    - include_tasks: tasks/defaults.yml
      tags: ['defaults']
    - include_tasks: tasks/keyboard.yml
      tags: ['keyboard', 'defaults']
