---
- name: Play feedback when volume is changed
  osx_defaults:
    key: com.apple.sound.beep.feedback
    type: int
    value: 1

- name: Disable user interface sound effects
  osx_defaults:
    key: com.apple.sound.uiaudio.enabled
    type: int
    value: 0

- name: Show sound icon in menubar
  osx_defaults:
    domain: com.apple.systemuiserver
    key: "NSStatusItem Visible com.apple.menuextra.volume"
    type: boolean
    value: 1
