---
- name: Play feedback when volume is changed
  osx_defaults:
    key: com.apple.sound.beep.feedback
    type: int
    value: 1

- name: Disable user interface sound effects
  osx_defaults:
    key: com.apple.sound.uiaudio.enabled
    type: int
    value: 0

- name: Show sound icon in menubar
  osx_defaults:
    domain: com.apple.systemuiserver
    key: "NSStatusItem Visible com.apple.menuextra.volume"
    type: boolean
    value: 1

- name: Set time format in menubar
  osx_defaults:
    domain: com.apple.menuextra.clock
    key: DateFormat
    type: string
    value: "EEE d MMM  HH:mm"

- name: Show bluetooth icon in menubar
  osx_defaults:
    domain: com.apple.systemuiserver
    key: "NSStatusItem Visible com.apple.menuextra.bluetooth"
    type: boolean
    value: 1

- name: Require password to disable screensaver
  osx_defaults:
    domain: com.apple.screensaver
    key: askForPassword
    value: 1

- name: Immediately require password to disable screensaver
  osx_defaults:
    domain: com.apple.screensaver
    key: askForPasswordDelay
    type: float
    value: 0
