---
- name: Repeat key presses more rapidly
  osx_defaults:
    key: KeyRepeat
    type: int
    value: 2

- name: Wait shorter time before starting to repeat key presses
  osx_defaults:
    key: InitialKeyRepeat
    type: int
    value: 15

- name: Press tab to move focus between all controls
  osx_defaults:
    key: AppleKeyboardUIMode
    type: int
    value: 2

- name: 'Disable "smart" quotes'
  osx_defaults:
    key: NSAutomaticQuoteSubstitutionEnabled
    type: boolean
    value: 0

- name: 'Disable "smart" dashes'
  osx_defaults:
    key: NSAutomaticDashSubstitutionEnabled
    type: boolean
    value: 0

- name: Disable automatic capitalization
  osx_defaults:
    key: NSAutomaticCapitalizationEnabled
    type: boolean
    value: 0

- name: Disable period on double space
  osx_defaults:
    key: NSAutomaticPeriodSubstitutionEnabled
    type: boolean
    value: 0

- name: Disable autocorrect
  osx_defaults:
    key: NSAutomaticSpellingCorrectionEnabled
    type: boolean
    value: 0

- name: Use F1, F2, etc. keys as standard function keys
  osx_defaults:
    key: com.apple.keyboard.fnState
    type: boolean
    value: 1

- name: Ensure ~/Library/KeyBindings exists
  file:
    path: "~/Library/KeyBindings"
    state: directory
    mode: 0755

- name: Configure default keybindings
  copy:
    src: files/keyboard/DefaultKeyBinding.dict
    dest: "~/Library/KeyBindings/DefaultKeyBinding.dict"

- name: Add custom keyboard layout
  copy:
    src: "files/keyboard/U.S. International - Modified.keylayout"
    dest: "/Library/Keyboard Layouts/U.S. International - Modified.keylayout"
  become: true

# See https://developer.apple.com/library/archive/technotes/tn2450/_index.html
# Macbook keyboard is VendorID=0x5ac/1452, ProductID=0x279/633
- name: Swap Control/Capslock on Macbook keyboard
  command:
    argv:
    - '/usr/bin/defaults'
    - '-currentHost'
    - 'write'
    - '-globalDomain'
    - 'com.apple.keyboard.modifiermapping.1452-633-0'
    - '<array><dict><key>HIDKeyboardModifierMappingSrc</key><integer>0x700000039</integer><key>HIDKeyboardModifierMappingDst</key><integer>0x7000000e4</integer></dict></array>'
